FROM golang:1.7-wheezy

#COPY distribution /go/src/github.com/docker/distribution
RUN go get github.com/docker/distribution/notifications
COPY reggie.go /go/src/
RUN CGO_ENABLED=0 go build -a /go/src/reggie.go
